version: "3.4"

services:
    minio:
        image: docker.io/bitnami/minio:latest
        container_name: IE-Minio
        restart: on-failure
        ports:
            - 9000:9000
            - ${MINIO_ADMIN_PORT}:9001
        volumes:
            - minio_data:/data
        env_file: .env

    mongodb:
        image: mongo:7.0.1
        container_name: IE-Mongo
        restart: on-failure
        ports:
            - 27017:27017
        volumes:
            - mongo_data:/data/db
        env_file: .env

    ie-backend:
        image: internetengineeringbackend
        container_name: IE-Backend
        build:
            context: .
            dockerfile: Internet-Engineering-Backend/Dockerfile
        ports:
            - ${SERVER_PORT}:80
        env_file: .env
        depends_on:
            - minio
            - mongodb

volumes:
    minio_data:
    mongo_data:
