namespace Internet_Engineering_Backend.Resources;

public enum Errors
{
	INVALID_LOGIN,
	INVALID_EMAIL,
	USERNAME_EXISTS,
	EMAIL_EXISTS,
	REGISTRATION_CLOSED,
	USER_NOT_FOUND,
	INVALID_KEY_LENGTH,
	INVALID_PASSWORD_LENGTH,
}
