namespace Internet_Engineering_Backend.Resources;

public enum Errors
{
	INVALID_LOGIN,
	INVALID_EMAIL,
	USERNAME_EXISTS,
	EMAIL_EXISTS,
	REGISTRATION_CLOSED,
	USER_NOT_FOUND,
	INVALID_PASSWORD_LENGTH,
	FOLDER_NOT_FOUND,
	FILE_NOT_FOUND,
	INVALID_NAME,
	STORAGE_LIMIT_EXCEEDED,
	FILE_NOT_SHARED,
	INVALID_USAGE_VALUE,
	INVALID_EXPIRY_DATE,
	INVALID_SHARE_URL,
	SHARE_EXPIRED,
}
